# Generated by Django 5.2.8 on 2025-12-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accused_id', models.CharField(max_length=100)),
                ('overall_result', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_prediction', models.CharField(max_length=50)),
                ('audio_prediction', models.CharField(max_length=50)),
                ('linguistic_analysis', models.CharField(max_length=50)),
                ('detailed_report', models.JSONField()),
            ],
        ),
    ]
