# Generated by Django 5.2.8 on 2025-12-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='accused_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
