# Generated by Django 4.2.7 on 2026-03-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0002_alter_report_accused_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='scenario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
